### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(OfflineInsiderEnroll2)
add_subdirectory(OfflineInsiderEnroll2Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    OfflineInsiderEnroll2plugin
    OfflineInsiderEnroll2Contentplugin
    QtQuickDesignerComponents)